Repository MSP-Tech-Club-MIU/MSP-MIU-Website, pull requests merged in 2025-10, with the labels that each got.

#3 add my project files
  src/form-google.css
  src/registration.jsx
Labels: Review effort 1/5

#4 Manual sync with main
  .gitignore
  app.js
  client/package-lock.json
  client/public/assets/index-B1Fw0J0q.js
  client/public/assets/index-CZLHMVpR.css
  client/public/assets/miu-logo-C9r327CS.png
  client/public/assets/msp-logo-C_Z3KgzA.png
  client/public/index.html
  client/src/index.js
  package-lock.json
  package.json
  scripts/pdfparse.py
  server/config/db.js
  server/controllers/applications.js
  server/controllers/board.js
  server/controllers/members.js
  server/models/Application.js
  server/models/Attendance.js
  server/models/Board.js
  server/models/Department.js
  server/models/Event.js
  server/models/Member.js
  server/models/Session.js
  server/models/index.js
  server/package.json
  server/routes/applications.js
  server/routes/board.js
  server/routes/members.js
  server/server.js
Labels: Review effort 2/5, Possible security concern

#5 Manual sync with main
  .gitignore
  client/index.html
  client/package.json
  client/src/App.jsx
  client/src/AppRouter.jsx
  client/src/assets/CSS/styles.css
  client/src/assets/Images/miu-logo.png
  client/src/assets/Images/msp-logo.png
  client/src/components/Dashboard.jsx
  client/src/data/departments.js
  client/src/main.jsx
  client/src/pages/ApplicationsPage.jsx
  client/src/services/api.js
  client/vite.config.js
  scripts/seed.sql
  server/.env
  server/app.js
Labels: Review effort 1/5

#9 Refactor Dashboard component to use ApiService for fetching and updat…
  client/src/components/Dashboard.jsx
Labels: Review effort 2/5

#11 Added Search functionality and improved table ui
  client/src/components/Dashboard.jsx
Labels: Review effort 2/5

#12 Add pie chart visualizations to Dashboard component for first choice,…
  client/src/components/Dashboard.jsx
Labels: Review effort 2/5

#14 Front end
  client/src/components/Dashboard.jsx
Labels: Review effort 2/5
